### ISSUE TITLE
amapCoupon.js抢券失败

### ISSUE THREAD

**Issue by breakmyhabits** [wf021325/qx#1]
amapDacheCoupon.js抢券失败
checkIn函数获取券列表失败，抓包发现请求两个in参数（网址和data各一个），现有版本用不了

**Comment by Andy963** [comment]
> amapDacheCoupon.js抢券失败 checkIn函数获取券列表失败，抓包发现请求两个in参数（网址和data各一个），现有版本用不了

解决了吗？
